name: "FTP Upload"
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to ftp server
    steps:
    - uses: actions/checkout@v2

    - name: 📂 Sync files
      uses: leandrorepos/ftp-deploy@1.0.0
      with:
        server: ftp.samkirkland.com
        username: ${{ secrets.FTP_HOST }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./data/
        server-dir: ./dev.rantk.com/
        security: loose
       
