on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to ftp server
    steps:
    - uses: actions/checkout@v2

    - name: Fast FTP Action
      uses: anvil-solutions/Fast-FTP-Action@2.1.0
      with:
        server: ftp.rantk.com
        port: 21
        username: ${{ secrets.HOST }}
        password: ${{ secrets.FTP_PASSWORD }}
